### PR TITLE
refactor: optimize `request.js`

### PR DESCRIPTION
**Pull request by pan93412**

### CODE REVIEW

**Comment by 1715173329** [comment]
```node
$ node app.js
/home/CN_SZTL/project/UnblockNeteaseMusic/src/request.js:93
		cancelRequest?.on(ON_CANCEL, destroyClientRequest);
		              ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/CN_SZTL/project/UnblockNeteaseMusic/src/hook.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by 1715173329** [comment]
> ```js
> $ node app.js
> /home/CN_SZTL/project/UnblockNeteaseMusic/src/request.js:93
> 		cancelRequest?.on(ON_CANCEL, destroyClientRequest);
> 		              ^
> 
> SyntaxError: Unexpected token .
>     at Module._compile (internal/modules/cjs/loader.js:723:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/home/CN_SZTL/project/UnblockNeteaseMusic/src/hook.js:4:17)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> 
> $ node -v
> v10.24.1
> ```

Well, works fine on node v14.17.5, it's okay.

**Review by 1715173329 — APPROVED** [review]

**Comment by pan93412** [comment]
> ```js
> ```js
> $ node app.js
> /home/CN_SZTL/project/UnblockNeteaseMusic/src/request.js:93
> 		cancelRequest?.on(ON_CANCEL, destroyClientRequest);
> 		              ^
> 
> SyntaxError: Unexpected token .
>     at Module._compile (internal/modules/cjs/loader.js:723:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (/home/CN_SZTL/project/UnblockNeteaseMusic/src/hook.js:4:17)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> 
> $ node -v
> v10.24.1
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Well, works fine on node v14.17.5, it's okay.
> ```

Try to disable the `DEVELOPMENT` mode? The precompiled version should work on Node 10 at least.

**Comment by 1715173329** [comment]
> Try to disable the DEVELOPMENT mode? The precompiled version should work on Node 10 at least.

Yes certainly I disabled it, but didn't work.
Well, just let node v10.x gone.

**Comment by pan93412** [comment]
> > Try to disable the DEVELOPMENT mode? The precompiled version should work on Node 10 at least.
> 
> Yes certainly I disabled it, but didn't work.
> Well, just let node v10.x gone, and we can make our source code cleaner.

```
pan93412:UnblockNeteaseMusic/ (refactor/request) $ node app.js        [7:01:08]
HTTP Server running @ http://0.0.0.0:8080
HTTPS Server running @ http://0.0.0.0:8081
^C
pan93412:UnblockNeteaseMusic/ (refactor/request) $ nvm use 10         [7:01:12]
Now using node v10.24.1 (npm v6.14.12)
pan93412:UnblockNeteaseMusic/ (refactor/request) $ node app.js        [7:01:19]
HTTP Server running @ http://0.0.0.0:8080
HTTPS Server running @ http://0.0.0.0:8081
^C
```

It works now :) I just made some mistakes on requiring package :(

**Comment by pan93412** [comment]
@1715173329 Better to `git reset --hard origin/enhanced`. I have squashed this branch.

**Comment by 1715173329** [comment]
> @1715173329 Better to `git reset --hard origin/enhanced`. I have squashed this branch.

Got it, thanks!

**Pull request merged**
