### PR TITLE
Update cert

### PR DESCRIPTION
**Pull request by Extreme-Icer**
Renew ca cert&server cert
ver0.27.5->0.27.6dev

### CODE REVIEW

**Review by pan93412 — APPROVED** [review]

**Comment by 1715173329** [comment]
@pan93412 is the original CA cert still on your device? My PC was exploded and needs at least one more day to fix.

**Comment by aliencaocao** [comment]
Just have to drop in replace right?

**Comment by Extreme-Icer** [comment]
> Just have to drop in replace right?

yes，only replace these files,if u want windows&linux files,see this:[https://github.com/Extreme-Icer/unm-server/releases/tag/0.27.6-dev](url)

**Comment by aliencaocao** [comment]
Thanks, im using docker, so I just shell into it and replaced both server.crt and server.key. Doesnt seem to be working though, after restarting it

**Comment by Extreme-Icer** [comment]
> 谢谢，我使用的是docker，所以我只是把它壳进去，并替换了server.crt和server.key。重新启动后似乎不起作用

ca cert+server cert all replace,try again

**Comment by aliencaocao** [comment]
I found out why. I was using ca cert from https://github.com/UnblockNeteaseMusic/server/issues/1373#issuecomment-1993671083 which I thought was same as what you PRed but its not. It works now

**Comment by aliencaocao** [comment]
I think you should link to https://github.com/UnblockNeteaseMusic/server/issues/1373 by adding "Closes https://github.com/UnblockNeteaseMusic/server/issues/1373" to your PR

**Comment by rcy17** [comment]
Thanks for your quick response on #1373. However, I don't think this is the best practice for the original issue.
@1715173329 generated a CA cert expired in 5 years, now he just needs to renew the server cert which expires per year, and this process won't be perceived by users as if he renews the server cert before expiration . But, if we regenerate the ca certs every year, users have to configure the trusted CA cert in each March.

**Comment by aliencaocao** [comment]
> But, if we regenerate the ca certs every year

This cert also valid for 5 year btw.

**Pull request closed without merging**
