### PR TITLE
Update youtube.js

### PR DESCRIPTION
**Pull request by 1582421598**

### CODE REVIEW

**Comment by 1582421598** [comment]
az，匹配push错分支了

**Comment by 1715173329** [comment]
What happened?

**Comment by 1715173329** [comment]
Thanks, and I've applied your commit d513a21ec0cd10.
But there's a issue: when song name contains `;`, this match will be broken.

**Comment by pan93412** [comment]
> Thanks, and I've applied your commit [d513a21](https://github.com/1715173329/UnblockNeteaseMusic/commit/d513a21ec0cd10851ee8d688ed36d9793a20dd7d).
> But there's a issue: when song name contains `;`, this match will be broken.

Is the length of the array split with `;` fixed? It would be better to match explicitly if yes.

**Comment by 1715173329** [comment]
I don't have any idea in handling this by now...

**Pull request closed without merging**
